#!/usr/bin/env python3
"""Writes the same multi-module program twice: once in iyi, once in Go.

`bench/build_speed/generate_pair.py` writes one file per language, which is
what a *full* build wants and says nothing about the claim this language is
built on. R-1 is about the second build: a module compiles against its
imports' declarations, so editing one module should cost that module and the
link, not the program. Go answers the same question with packages, and answers
it well, which is why it is the column to stand next to.

So this writes a project rather than a file: `modules` modules of
`types_per_module` types each, one `main` that calls into every one of them,
and the same shape again in Go with one package per module. Neither half is
written by hand, both come out of the numbers below, and `incremental.py`
refuses to time them until the two binaries print the same thing.

The types are the ones `generate_pair.py` uses, for the same reason it gives:
dull on purpose, identical in both languages, and everything stays inside
`% 1000` because Crystal's `Int32` raises on overflow where Go's wraps.
"""

import pathlib
import sys

MODULES = 30
TYPES_PER_MODULE = 10


def widget_iyi(index):
    return f"""
pub struct Widget{index}
  @a : Int32
  @b : Int32

  def initialize(@a : Int32, @b : Int32)
  end

  def score : Int32
    ((@a * {3 + index % 7}) + (@b * {5 + index % 11})) % 1000
  end

  def blend(other : Widget{index}) : Int32
    (score + other.score) % 1000
  end

  def label : String
    "widget-{index}"
  end
end
"""


def widget_go(index):
    return f"""
type Widget{index} struct {{
	a int32
	b int32
}}

func (w Widget{index}) Score() int32 {{
	return ((w.a * {3 + index % 7}) + (w.b * {5 + index % 11})) % 1000
}}

func (w Widget{index}) Blend(other Widget{index}) int32 {{
	return (w.Score() + other.Score()) % 1000
}}

func (w Widget{index}) Label() string {{
	return "widget-{index}"
}}
"""


def module_iyi(part, indices):
    """One module: its types, and the one exported function main calls."""
    body = [
        "# Generated by bench/incremental/generate_project.py — do not edit.",
        f"module parts/mod{part}",
    ]
    body += [widget_iyi(index) for index in indices]
    body.append(f"\npub def total{part} : Int32")
    # The one line this bench edits. It is here rather than inside a generated
    # method because the generated numbers repeat across widgets, and an edit
    # that hits more than one of them is not the same edit in both languages.
    body.append("  edit_point = 0")
    body.append("  total = edit_point")
    for index in indices:
        a, b = index % 97, index % 89
        body.append(f"  w{index} = Widget{index}.new({a}, {b})")
        body.append(
            f"  total = (total + w{index}.score + w{index}.blend(w{index}) + w{index}.label.size) % 100000"
        )
    body.append("  total")
    body.append("end")
    return "\n".join(body) + "\n"


def module_go(part, indices):
    body = [
        "// Generated by bench/incremental/generate_project.py — do not edit.",
        f"package mod{part}",
    ]
    body += [widget_go(index) for index in indices]
    body.append(f"\nfunc Total{part}() int32 {{")
    body.append("\tvar editPoint int32 = 0")
    body.append("\tvar total int32 = editPoint")
    for index in indices:
        a, b = index % 97, index % 89
        body.append(f"\tw{index} := Widget{index}{{a: {a}, b: {b}}}")
        body.append(
            f"\ttotal = (total + w{index}.Score() + w{index}.Blend(w{index}) + int32(len(w{index}.Label()))) % 100000"
        )
    body.append("\treturn total")
    body.append("}")
    return "\n".join(body) + "\n"


def main_iyi(modules):
    lines = [
        "# Generated by bench/incremental/generate_project.py — do not edit.",
        "module bench/incremental",
        "",
    ]
    lines += [f"import parts/mod{part}" for part in range(modules)]
    lines += ["", "total = 0"]
    for part in range(modules):
        lines.append(f"total = (total + Parts::Mod{part}.total{part}) % 1000000")
    lines += ["", "puts total", ""]
    return "\n".join(lines)


def main_go(modules):
    lines = [
        "// Generated by bench/incremental/generate_project.py — do not edit.",
        "package main",
        "",
        "import (",
        '\t"fmt"',
    ]
    lines += [f'\t"bench/incremental/parts/mod{part}"' for part in range(modules)]
    lines += [")", "", "func main() {", "\tvar total int32 = 0"]
    for part in range(modules):
        lines.append(f"\ttotal = (total + mod{part}.Total{part}()) % 1000000")
    lines += ["", "\tfmt.Println(total)", "}", ""]
    return "\n".join(lines)


def write_project(directory, modules=MODULES, types_per_module=TYPES_PER_MODULE):
    """Writes both projects under *directory*, returning (iyi_root, go_root)."""
    directory = pathlib.Path(directory)
    iyi_root = directory / "iyi"
    go_root = directory / "go"
    (iyi_root / "parts").mkdir(parents=True, exist_ok=True)
    go_root.mkdir(parents=True, exist_ok=True)

    for part in range(modules):
        indices = range(part * types_per_module, (part + 1) * types_per_module)
        (iyi_root / "parts" / f"mod{part}.iyi").write_text(module_iyi(part, indices))
        package = go_root / "parts" / f"mod{part}"
        package.mkdir(parents=True, exist_ok=True)
        (package / f"mod{part}.go").write_text(module_go(part, indices))

    (iyi_root / "main.iyi").write_text(main_iyi(modules))
    (go_root / "main.go").write_text(main_go(modules))
    (go_root / "go.mod").write_text("module bench/incremental\n\ngo 1.21\n")
    return iyi_root, go_root


if __name__ == "__main__":
    target = sys.argv[1] if len(sys.argv) > 1 else "."
    iyi_root, go_root = write_project(target)
    lines = sum(len(p.read_text().splitlines()) for p in iyi_root.rglob("*.iyi"))
    print(f"{iyi_root}: {MODULES} modules, {MODULES * TYPES_PER_MODULE} types, {lines} lines")
    print(f"{go_root}: the same, as Go packages")
